input {
  file {
    path => "/logstash_dir/logs/training.jsonl"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb-training"
    codec => json
    mode => tail
    stat_interval => 1
  }
  file {
    path => "/logstash_dir/logs/serving.jsonl"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb-serving"
    codec => json
    mode => tail
    stat_interval => 1
  }
}

filter {
  if [timestamp] {
    date {
      match => [ "timestamp", "ISO8601" ]
      target => "@timestamp"
    }
  }
}

output {
  if [dataset] == "ml.training" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ml-training-%{+YYYY.MM.dd}"
    }
  } else if [dataset] == "ml.serving" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ml-serving-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ml-other-%{+YYYY.MM.dd}"
    }
  }
}
